/*
 * ==================================================================================
 * FILE: TickSource.java
 * ==================================================================================
 *
 * WHAT THIS FILE DOES:
 * This tells us WHERE a stock tick came from — did we make it up (simulation),
 * or did it come from a real stock exchange (live)?
 *
 * WHY IT MATTERS:
 * The frontend shows different things based on this:
 * - SIMULATION → Shows prices in Indian Rupees (₹) with NSE exchange tags
 * - LIVE_PROVIDER → Shows prices in US Dollars ($) with NASDAQ/NYSE exchange tags
 * ==================================================================================
 */

package com.quantstream.backend.domain;

public enum TickSource {
    SIMULATION,     // Fake data generated by our app for testing/demo (NSE Indian stocks)
    LIVE_PROVIDER   // Real market data from Finnhub WebSocket API (US stocks like AAPL, MSFT, etc.)
}
